default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV.fetch("MYSQL_USERNAME", "root") %>
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  host: <%= ENV.fetch("MYSQL_HOST", "db") %>

development:
  <<: *default
  database: myapp_development

test:
  <<: *default
  database: myapp_test

production:
  <<: *default
  database: production
  username: admin
  password: <%= ENV.fetch("MYSQL_PASSWORD", "password") %>
  host: production.c6xivzgib2j5.ap-northeast-1.rds.amazonaws.com
  socket: /var/lib/mysql/mysql.sock
